version: "3"
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=roz
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=157
    volumes:
      - ./sql/schema/college.sql:/docker-entrypoint-initdb.d/init.sql