// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.insertCourseStmt, err = db.PrepareContext(ctx, insertCourse); err != nil {
		return nil, fmt.Errorf("error preparing query InsertCourse: %w", err)
	}
	if q.insertDepartmentStmt, err = db.PrepareContext(ctx, insertDepartment); err != nil {
		return nil, fmt.Errorf("error preparing query InsertDepartment: %w", err)
	}
	if q.selectStudentsStmt, err = db.PrepareContext(ctx, selectStudents); err != nil {
		return nil, fmt.Errorf("error preparing query SelectStudents: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.insertCourseStmt != nil {
		if cerr := q.insertCourseStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertCourseStmt: %w", cerr)
		}
	}
	if q.insertDepartmentStmt != nil {
		if cerr := q.insertDepartmentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertDepartmentStmt: %w", cerr)
		}
	}
	if q.selectStudentsStmt != nil {
		if cerr := q.selectStudentsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing selectStudentsStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                   DBTX
	tx                   *sql.Tx
	insertCourseStmt     *sql.Stmt
	insertDepartmentStmt *sql.Stmt
	selectStudentsStmt   *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                   tx,
		tx:                   tx,
		insertCourseStmt:     q.insertCourseStmt,
		insertDepartmentStmt: q.insertDepartmentStmt,
		selectStudentsStmt:   q.selectStudentsStmt,
	}
}
