// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type Course struct {
	Name         sql.NullString `json:"name"`
	ID           int64          `json:"id"`
	InstructorID sql.NullInt32  `json:"instructor_id"`
	DepartmentID sql.NullInt32  `json:"department_id"`
}

type Department struct {
	ID    int64          `json:"id"`
	Name  sql.NullString `json:"name"`
	HodID sql.NullInt32  `json:"hod_id"`
}
